import json, subprocess, sys, tempfile, unittest
from pathlib import Path
from _engine import ROOT, ENGINE, SCRIPTS
sys.path.insert(0, str(SCRIPTS))
import install_hooks as ih

OLD_GLOBAL = '"C:/Python/python.exe" "C:/Users/u/.claude/skills/aip/scripts/aip_overview.py" --repo-root . --print'
OTHER = 'python "$CLAUDE_PROJECT_DIR/scripts/mine.py"'

def repo_with_settings(starts) -> Path:
    d = Path(tempfile.mkdtemp())
    (d/".claude").mkdir()
    (d/".claude"/"settings.json").write_text(json.dumps({"hooks": {"SessionStart": starts}}), encoding="utf-8")
    return d

def commands(d: Path) -> list[str]:
    data = json.loads((d/".claude"/"settings.json").read_text(encoding="utf-8"))
    return [h["command"] for g in data["hooks"]["SessionStart"] for h in g["hooks"]]

class SessionStartHook(unittest.TestCase):
    def test_project_engine_uses_portable_command(self):
        d = repo_with_settings([])
        ih.install_claude_session_start(d, d/".claude"/"skills"/"aip")
        [cmd] = commands(d)
        self.assertTrue(cmd.startswith("for py in python3 python;"), cmd)   # 先 python3 再 python
        self.assertIn('"$CLAUDE_PROJECT_DIR/.claude/skills/aip/scripts/aip_session_start.py" '
                      '--repo-root "$CLAUDE_PROJECT_DIR"', cmd)

    @unittest.skipIf(sys.platform == "win32", "要 POSIX sh")
    def test_portable_command_refuses_python2_and_runs_python3(self):
        d = repo_with_settings([])
        engine = d/".claude"/"skills"/"aip"
        (engine/"scripts").mkdir(parents=True)
        (engine/"scripts"/"aip_session_start.py").write_text("import sys; print('跑了', sys.version_info[0])\n",
                                                             encoding="utf-8")
        cmd = ih.session_start_cmd(d, engine)
        bin_dir = Path(tempfile.mkdtemp())
        fake2 = bin_dir/"python"
        fake2.write_text("#!/bin/sh\nexit 1\n", encoding="utf-8"); fake2.chmod(0o755)   # 版本检查不过，就像 Python 2
        env = {"PATH": str(bin_dir), "CLAUDE_PROJECT_DIR": str(d)}
        out = subprocess.run(["/bin/sh", "-c", cmd], env=env, capture_output=True, text=True, encoding="utf-8")
        self.assertEqual(out.returncode, 0); self.assertIn("没找到 Python 3.9", out.stdout)
        (bin_dir/"python3").symlink_to(sys.executable)
        out = subprocess.run(["/bin/sh", "-c", cmd], env=env, capture_output=True, text=True, encoding="utf-8")
        self.assertIn("跑了 3", out.stdout); self.assertNotIn("没找到", out.stdout)

    def test_engine_outside_repo_keeps_absolute_command(self):
        d = repo_with_settings([])
        outside = Path(tempfile.mkdtemp())/"aip"
        ih.install_claude_session_start(d, outside)
        self.assertIn(outside.as_posix(), commands(d)[0])

    def test_stale_aip_hook_replaced_and_others_kept(self):
        d = repo_with_settings([{"hooks": [{"type": "command", "command": OLD_GLOBAL},
                                           {"type": "command", "command": OTHER}]}])
        ih.install_claude_session_start(d, d/".claude"/"skills"/"aip")
        cmds = commands(d)
        self.assertNotIn(OLD_GLOBAL, cmds)
        self.assertIn(OTHER, cmds)
        self.assertEqual(sum("aip_session_start.py" in c for c in cmds), 1)

    def test_rerun_is_idempotent(self):
        d = repo_with_settings([])
        engine = d/".claude"/"skills"/"aip"
        ih.install_claude_session_start(d, engine)
        ih.install_claude_session_start(d, engine)
        self.assertEqual(len(commands(d)), 1)

class NoPreCommit(unittest.TestCase):
    def test_existing_foreign_pre_commit_left_alone(self):
        d = repo_with_settings([])
        hooks = d/".git"/"hooks"; hooks.mkdir(parents=True)
        (hooks/"pre-commit").write_text("#!/bin/sh\n# File generated by pre-commit\n", encoding="utf-8")
        engine = d/".claude"/"skills"/"aip"
        r = subprocess.run([sys.executable, str(SCRIPTS/"install_hooks.py"), "--repo-root", str(d),
                            "--engine-root", str(engine), "--session-start", "--no-pre-commit"],
                           capture_output=True, text=True, encoding="utf-8")
        self.assertEqual(r.returncode, 0, r.stderr)
        self.assertIn("File generated by pre-commit", (hooks/"pre-commit").read_text(encoding="utf-8"))
        self.assertEqual(len(commands(d)), 1)

if __name__ == "__main__":
    unittest.main()
